# Settings
url: https://lufevida.github.io
baseurl: /html5up-multiverse
title: Multiverse
tagline: by HTML5 Up
footerTitle: Magna feugiat sed adipiscing
footerTagline: Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum eget quis orci mattis aliquet. Maecenas fringilla et ante at lorem et ipsum. Dolor nulla eu bibendum sapien. Donec non pharetra dui. Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum.
copyright: Untitled

# Contact
email: name@provider.com
twitter: username
facebook: username
instagram: username
github: username
dribble: username
linkedin: username